<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SignIn</name>
   <tag></tag>
   <elementGuidId>f550a6e4-5ea1-4808-9a0e-2143d3de384d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type=&quot;submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@type=&quot;submit&quot;]</value>
      <webElementGuid>1043788c-d0a3-4853-890b-dd1ecdb70d4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
